### ISSUE TITLE
Decide whether Home and Notifications channels should be in the channel list

### ISSUE THREAD

**Issue by EdwardHinkle** [indieweb/microsub#16]
Over in the Aperture project, the question about if Home and Notifications channels should be returned in the channel list or not was raised. (https://github.com/aaronpk/Aperture/issues/16) 

The current thinking from that issue is:

- Location: Do clients plan on Home and Notifications being within the normal list of channels or outside that list as separate interface elements?
- Ordering: Related to Location, is it expected that a user can re-order Home and Notifications within the list of channels?
- Localization: All the normal channel titles will automatically be returned in the Microsub server's localized language. If Home and Notifications aren't in the list, it is up to the app to localize Home and Notifications, which may or may not be a challenge to match the localization of the Microsub server without those features built in to the spec.

**Comment by aaronpk** [comment]
Some silo examples of "home" vs "notifications":

![Twitter](https://media.aaronpk.com/Screen-Shot-2018-02-11-09-24-11-GX23DbVUXP.jpg)

![GitHub](https://media.aaronpk.com/Screen-Shot-2018-02-11-09-57-21-IyH2lgGrvt.jpg)

![Facebook](https://media.aaronpk.com/Screen-Shot-2018-02-11-09-57-49-6ugb6uPg8b.jpg)

and of course more [on the wiki](https://indieweb.org/notification#Silo_Examples)

[Some discussion from IRC](https://chat.indieweb.org/2018-02-11#t1518371157576800) about whether hardcoding a "home" channel even makes sense in the first place.

**Comment by aaronpk** [comment]
Okay, it sounds like we have a proposal for some changes around how these channels are handled:

* The only special uid is `notifications`
* A Microsub server is required to start with a single "Home" channel, the uid can be whatever it wants
* Users can remove or rename the initial default channel
* Servers MUST return the `notifications` channel as the first channel in the list
* Servers MUST ignore the `notifications` channel when reordering channels
* Clients SHOULD show the `notifications` channel separately in the UI

**Comment by aaronpk** [comment]
[Here is a diff of the changes](https://indieweb.org/wiki/index.php?title=Microsub-spec&type=revision&diff=45235&oldid=44925).

The main differences can be read here:

* [Channels](https://indieweb.org/Microsub-spec#Channels)
* [Retrieve the list of channels](https://indieweb.org/Microsub-spec#Channels_2)

**Comment by aaronpk** [comment]
[Here is a diff of the changes](https://indieweb.org/wiki/index.php?title=Microsub-spec&type=revision&diff=45235&oldid=44925).

The main differences can be read here:

* [Channels](https://indieweb.org/Microsub-spec#Channels)
* [Retrieve the list of channels](https://indieweb.org/Microsub-spec#Channels_2)
