### ISSUE TITLE
Standardisation of Content

### ISSUE THREAD

**Issue by dg01d** [indieweb/microsub#22]
Not sure how this one should be marked up, but however:

The non-standardisation of content delivered is an inhibitor of adoption. There are simply too many if..then's when looking at even the most basic of feeds. While it is appreciated that microsub is merely delivering the content from other locations, does the opportunity not exist to standardise the output?

A standardised set of output, being necessarily limited, would expose a smaller set of variables on examination of the resultant markup, thus accelerating consumption models and improving diversity in the `reader` ecosystem.

**Comment by aaronpk** [comment]
Can you provide examples of what you're finding that is not normalized?

Microsub is *not* "merely delivering the content from other locations". Microsub is in fact specifically already doing a *lot* of normalization of the content it finds, producing a feed that is much more standardized than what it discovered when crawling the feeds, even to the point of making vocabulary-specific decisions about some values.
