### ISSUE TITLE
Preview: how to handle multiple feeds?

### ISSUE THREAD

**Issue by sknebel** [indieweb/microsub#26]
Pages often advertise multiple feeds (especially with RSS/Atom), and a microsub server might want to give the user a preview/choice of all of them before one is picked to subscribe to.

Examples: category pages offering both a feed for the category and the overall site, or permalinks offering the overall site and the comments on the page.

First idea: The preview call for a URL could either return a list of timelines, or just a list of URLs with titles (if given in e.g. the `<link>` tags referencing the feeds) and let the client pick which timeline to actually fetch.

**Comment by aaronpk** [comment]
This is handled with the `search` action already, although could probably use some improvement. Here's what it looks like in Together:

![search](https://media.aaronpk.com/Screen-Shot-2018-03-12-11-43-47-if9CQIv1a7.jpg)

**Comment by sknebel** [comment]
Oops, somehow had `search` filed unter content search, not this. Confusing name IMHO, but I guess the functionality is there. Sorry for the noise.
