### ISSUE TITLE
Url of Feed as post property

### ISSUE THREAD

**Issue by EdwardHinkle** [indieweb/microsub#32]
So I am often reading my timeline and decide I want to remove a person’s feed. Sometimes I know their feed and I can just pick the one I want to remove.

Other times, I don’t. It won’t be nice if there was a _feed property on the jf2 post objects that gave you the url of the feed. This would allow a reader to give an option like “unsubscribe from this feed” on a contextual menu of a post. The user would have to figure out which feed it was on. It could ask for confirmation and maybe display a preview of that feeds recent posts so you know what you’re unsubscribing from.

**Comment by mblaney** [comment]
I think this is the same as #13 yeah?

**Comment by EdwardHinkle** [comment]
Ohhh you’re right. I was confused and thought that was something else.
